# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana-service
# spec:
#   selector:
#     app: grafana
#   ports:
#     - port: 3000
#       targetPort: 3000
#   type: LoadBalancer
  
  service:
  port: 80
  targetPort: 3000
    # targetPort: 4181 To be used with a proxy extraContainer
  annotations: {}
  labels: {}
  portName: service

  ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
  hosts:
    - host: aa1c52ffae26642df850ecd953f35f02-550049158.us-east-1.elb.amazonaws.com
      paths:
        - /
