---
grafana:
  replicas: 1
  image:
    repository: grafana/grafana
    tag: 9.0.1
    sha: ""
    pullPolicy: IfNotPresent
  serviceAccount:
    autoMount: true
  ingress:
    enabled: false
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt-prod
      cert-manager.io/issue-temporary-certificate: "true"
      acme.cert-manager.io/http01-edit-in-place: "true"
    labels: {}
    path: /
    pathType: Prefix
    hosts:
      - grafana.dev.bitovi-staffing.com
    extraPaths: []
    tls:
      - secretName: grafana-tls
        hosts:
          - grafana.dev.bitovi-staffing.com
  adminUser: admin
  admin:
    existingSecret: ""
    userKey: admin-user
    passwordKey: admin-password
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: kubernetes
          orgId: 1
          folder: kubernetes
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/kubernetes
  dashboards:
    kubernetes:
      k8s-addons-starboard-operator:
        gnetId: 16337
        datasource: Prometheus
      k8s-system-api-server:
        gnetId: 15761
        datasource: Prometheus
      k8s-system-coredns:
        gnetId: 15762
        datasource: Prometheus
      k8s-views-global:
        gnetId: 15757
        datasource: Prometheus
      k8s-views-namespaces:
        gnetId: 15758
        datasource: Prometheus
      k8s-views-nodes:
        gnetId: 15759
        datasource: Prometheus
      k8s-views-pods:
        gnetId: 15760
        datasource: Prometheus
  grafana.ini:
    paths:
      data: /var/lib/grafana/data
      logs: /var/log/grafana
      plugins: /var/lib/grafana/plugins
      provisioning: /etc/grafana/provisioning
    analytics:
      check_for_updates: true
    log:
      mode: console
    grafana_net:
      url: https://grafana.net
  ldap:
    enabled: false
    existingSecret: ""
    config: ""
  smtp:
    existingSecret: ""
    userKey: user
    passwordKey: password
