name: Basic deploy
on:
  push:
    branches: [ bitops-conditional-helm ]

jobs:
  Deploy-Cluster:
    runs-on: ubuntu-latest

    steps:
    - name: Create EKS Cluster
      uses: bitovi/github-actions-deploy-eks@bitops-conditional-helm
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX}}
        aws_default_region: us-east-1
        aws_eks_cluster_admin_role_arn: arn:aws:iam::755521597925:role/AWSReservedSSO_AdministratorAccess_402f22a297379e03
        aws_eks_create: true
        # input_helm_charts:
        # tf_stack_destroy: true
        tf_state_bucket_destroy: true
        prometheus_enable: true
        grafana_enable: true
        loki_enable: true
        nginx_enable: true
#2nd
