name: Deploy EKS Cluster

on:
  push:
    branches: [ karam-helm-task ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy Helm
      uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
        cluster-name: mycluster
        cluster-role-arn: ${{ secrets.AWS_ROLE_ARN }}
        config-files: operations/deployment/helm/grafana/values.yaml
        chart-path: operations/deployment/helm/grafana
        namespace: monitoring
        name: grafana
        chart-repository: https://github.com/grafana/helm-charts
        version: 7.0.13
        atomic: true