name: Deploy EKS Cluster

on:
  push:
    branches: [ eks-helm-test ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy Grafana
       uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
         aws-region: us-east-1
         config-files: https://github.com/bitovi/deploy-helm-charts/blob/leo-helm/operations/deployment/helm/grafana/values.yaml
         chart-path: grafana/grafana
         namespace: lmonitoring
         name: leo-grafana
         chart-repository: https://grafana.github.io/helm-charts
         version: 7.0.11
         cluster-name: bitovi-deploy-helm-charts-karam-helm-task-cluster
         timeout: 30s

    # - name: Deploy Helm
    #   uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
    #   with:
    #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
    #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
    #     aws-region: us-west-1
    #     config-files: operations/deployment/helm/grafana/values.yaml
    #     chart-path: operations/deployment/helm/grafana
    #     namespace: monitoring
    #     name: grafana
    #     chart-repository: https://github.com/grafana/helm-charts
    #     version: 7.0.13
    #     atomic: true