name: Deploy EKS Cluster

on:
  push:
    branches: [ eks-helm-test ]
      

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
     - name: Deploy Grafana
       uses: bitovi/github-actions-deploy-eks-helm@v1.2.8
       with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SANDBOX }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SANDBOX }}
         aws-region: us-east-1
         config-files: https://github.com/bitovi/deploy-helm-charts/blob/eks-helm-test/operations/deployment/helm/grafana/values.yaml                
         chart-path: grafana/grafana
         namespace: kmonitoring
         name: karam-grafana
         chart-repository: https://grafana.github.io/helm-charts
         version: 7.0.11
         cluster-name: bitovi-deploy-helm-charts-karam-helm-task-cluster
         timeout: 30s